/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instalador2021;

import java.awt.Menu;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Alejandro
 */
public class activadoresPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form officePanel
     */
    public activadoresPanel() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        officeGroup = new javax.swing.ButtonGroup();
        InstalarOfficeBotton = new javax.swing.JButton();
        WordIcon = new javax.swing.JLabel();
        actWin7 = new javax.swing.JRadioButton();
        actWin10 = new javax.swing.JRadioButton();
        actOffice10 = new javax.swing.JRadioButton();
        actOffice16 = new javax.swing.JRadioButton();
        actKSM = new javax.swing.JRadioButton();
        actWin7B = new javax.swing.JRadioButton();
        imgAdorno = new javax.swing.JLabel();
        circulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(84, 115, 232));
        setBorder(null);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstalarOfficeBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        InstalarOfficeBotton.setText("Instalar");
        InstalarOfficeBotton.setBorder(null);
        InstalarOfficeBotton.setEnabled(false);
        InstalarOfficeBotton.setPreferredSize(new java.awt.Dimension(93, 29));
        InstalarOfficeBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstalarOfficeBottonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InstalarOfficeBottonMouseEntered(evt);
            }
        });
        InstalarOfficeBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstalarOfficeBottonActionPerformed(evt);
            }
        });
        getContentPane().add(InstalarOfficeBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 110, 30));

        WordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/programming-48.png"))); // NOI18N
        getContentPane().add(WordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        actWin7.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(actWin7);
        actWin7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actWin7.setForeground(new java.awt.Color(255, 255, 255));
        actWin7.setText("Activar Windows 7");
        actWin7.setBorder(null);
        actWin7.setContentAreaFilled(false);
        actWin7.setFocusPainted(false);
        actWin7.setFocusable(false);
        actWin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actWin7ActionPerformed(evt);
            }
        });
        getContentPane().add(actWin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, -1));

        actWin10.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(actWin10);
        actWin10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actWin10.setForeground(new java.awt.Color(255, 255, 255));
        actWin10.setText("Activar Windows 8-10");
        actWin10.setBorder(null);
        actWin10.setFocusPainted(false);
        actWin10.setOpaque(false);
        actWin10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actWin10ActionPerformed(evt);
            }
        });
        getContentPane().add(actWin10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 200, -1));

        actOffice10.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(actOffice10);
        actOffice10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actOffice10.setForeground(new java.awt.Color(255, 255, 255));
        actOffice10.setText("Activar Office 2010");
        actOffice10.setBorder(null);
        actOffice10.setFocusPainted(false);
        actOffice10.setOpaque(false);
        actOffice10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actOffice10ActionPerformed(evt);
            }
        });
        getContentPane().add(actOffice10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 200, -1));

        actOffice16.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(actOffice16);
        actOffice16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actOffice16.setForeground(new java.awt.Color(255, 255, 255));
        actOffice16.setText("Activar Office 2013-19");
        actOffice16.setBorder(null);
        actOffice16.setFocusPainted(false);
        actOffice16.setOpaque(false);
        actOffice16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actOffice16ActionPerformed(evt);
            }
        });
        getContentPane().add(actOffice16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        actKSM.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(actKSM);
        actKSM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actKSM.setForeground(new java.awt.Color(255, 255, 255));
        actKSM.setText("Activador universal KMS");
        actKSM.setBorder(null);
        actKSM.setFocusPainted(false);
        actKSM.setOpaque(false);
        actKSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actKSMActionPerformed(evt);
            }
        });
        getContentPane().add(actKSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, -1));

        actWin7B.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(actWin7B);
        actWin7B.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actWin7B.setForeground(new java.awt.Color(255, 255, 255));
        actWin7B.setText("Activador Windows 7 (Alternativo)");
        actWin7B.setBorder(null);
        actWin7B.setFocusPainted(false);
        actWin7B.setOpaque(false);
        actWin7B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actWin7BActionPerformed(evt);
            }
        });
        getContentPane().add(actWin7B, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 270, -1));

        imgAdorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PC4.png"))); // NOI18N
        getContentPane().add(imgAdorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, 200));

        circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circulo.png"))); // NOI18N
        getContentPane().add(circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InstalarOfficeBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstalarOfficeBottonMouseClicked

    }//GEN-LAST:event_InstalarOfficeBottonMouseClicked

    private void InstalarOfficeBottonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstalarOfficeBottonMouseEntered

    }//GEN-LAST:event_InstalarOfficeBottonMouseEntered

    private void InstalarOfficeBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstalarOfficeBottonActionPerformed
        JOptionPane.showMessageDialog(null, new JLabel("DESACTIVA EL ANTIVIRUS PRIMERO", JLabel.LEFT), "ALERTA", JOptionPane.WARNING_MESSAGE);
        Instalador activador = new Instalador();

        Procesos Buscador = new Procesos();
        try {
            String dato = Buscador.consoleInfo("Nombre del sistema operativo:", "systeminfo");
            if (dato.contains("Microsoft Windows 1")) {

                int result = JOptionPane.showConfirmDialog(null, "¿Desea abrir configuración de Windows Defender?", "",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    activador.instalar("explorer.exe windowsdefender:");
                }

            }
        } catch (IOException ex) {
            Logger.getLogger(activadoresPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        DescomprimirZip Extractor = new DescomprimirZip();
        if (actWin7.isSelected()) {
            try {
                Extractor.Descomprimir("Activadores/RemoveWAT.zip");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al descomprimir" + ex, "ERROR", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            activador.instalar("cmd /C start /wait Activadores/RemoveWAT.exe");
        }
        if (actOffice10.isSelected()) {
            try {
                Extractor.Descomprimir("Activadores/Office10.zip");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al descomprimir" + ex, "ERROR", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            activador.instalar("cmd /C start /wait Activadores/Office10.exe");
        }
        if (actOffice16.isSelected() | actWin10.isSelected()) {
            try {
                Extractor.Descomprimir("Activadores/Office16.zip");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al descomprimir" + ex, "ERROR", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            activador.instalar("cmd /C start /wait Activadores/Office16.exe");
        }
        if (actKSM.isSelected()) {
            try {
                Extractor.Descomprimir("Activadores/KMSpico.zip");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al descomprimir" + ex, "ERROR", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            activador.instalar("cmd /C start /wait Activadores/KMSpico.exe");
        }

        if (actWin7B.isSelected()) {
            try {
                Extractor.Descomprimir("Activadores/win7B.zip");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al descomprimir" + ex, "ERROR", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            activador.instalar("cmd /C start /wait Activadores/WindowsLoader.exe");
        }


    }//GEN-LAST:event_InstalarOfficeBottonActionPerformed

    private void actWin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actWin7ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_actWin7ActionPerformed

    private void actWin10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actWin10ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_actWin10ActionPerformed

    private void actOffice10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actOffice10ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_actOffice10ActionPerformed

    private void actOffice16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actOffice16ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_actOffice16ActionPerformed

    private void actKSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actKSMActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_actKSMActionPerformed

    private void actWin7BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actWin7BActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_actWin7BActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InstalarOfficeBotton;
    private javax.swing.JLabel WordIcon;
    private javax.swing.JRadioButton actKSM;
    private javax.swing.JRadioButton actOffice10;
    private javax.swing.JRadioButton actOffice16;
    private javax.swing.JRadioButton actWin10;
    private javax.swing.JRadioButton actWin7;
    private javax.swing.JRadioButton actWin7B;
    private javax.swing.JLabel circulo;
    private javax.swing.JLabel imgAdorno;
    private javax.swing.ButtonGroup officeGroup;
    // End of variables declaration//GEN-END:variables
}
