/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instalador2021;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Alejandro
 */
public class herramientasPanel extends javax.swing.JInternalFrame {

    Instalador herramientas = new Instalador();

    /**
     * Creates new form officePanel
     */
    public herramientasPanel() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoNetFramework = new javax.swing.JLabel();
        crystalDiskInfo = new javax.swing.JRadioButton();
        controlCuentas = new javax.swing.JRadioButton();
        logoRayosX = new javax.swing.JLabel();
        estadoBateria = new javax.swing.JRadioButton();
        adminDispositivos = new javax.swing.JRadioButton();
        logoConsola1 = new javax.swing.JLabel();
        netFramework452 = new javax.swing.JRadioButton();
        netFramework4 = new javax.swing.JRadioButton();
        netFramework35 = new javax.swing.JRadioButton();
        imgAdorno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(84, 115, 232));
        setBorder(null);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoNetFramework.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/net-framework-48.png"))); // NOI18N
        getContentPane().add(logoNetFramework, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        crystalDiskInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crystalDiskInfo.setForeground(new java.awt.Color(255, 255, 255));
        crystalDiskInfo.setText("Ver estado de Salud HDD/SSD");
        crystalDiskInfo.setBorder(null);
        crystalDiskInfo.setFocusPainted(false);
        crystalDiskInfo.setOpaque(false);
        crystalDiskInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crystalDiskInfoActionPerformed(evt);
            }
        });
        getContentPane().add(crystalDiskInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        controlCuentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        controlCuentas.setForeground(new java.awt.Color(255, 255, 255));
        controlCuentas.setText("Control de permisos");
        controlCuentas.setBorder(null);
        controlCuentas.setFocusPainted(false);
        controlCuentas.setOpaque(false);
        controlCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlCuentasActionPerformed(evt);
            }
        });
        getContentPane().add(controlCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        logoRayosX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x-ray-48.png"))); // NOI18N
        getContentPane().add(logoRayosX, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        estadoBateria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estadoBateria.setForeground(new java.awt.Color(255, 255, 255));
        estadoBateria.setText("Ver estado de la bateria");
        estadoBateria.setToolTipText("Solo Windows 10");
        estadoBateria.setBorder(null);
        estadoBateria.setFocusPainted(false);
        estadoBateria.setOpaque(false);
        estadoBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoBateriaActionPerformed(evt);
            }
        });
        getContentPane().add(estadoBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        adminDispositivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminDispositivos.setForeground(new java.awt.Color(255, 255, 255));
        adminDispositivos.setText("Administrador de Dispositivos");
        adminDispositivos.setBorder(null);
        adminDispositivos.setFocusPainted(false);
        adminDispositivos.setOpaque(false);
        adminDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDispositivosActionPerformed(evt);
            }
        });
        getContentPane().add(adminDispositivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        logoConsola1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/run-command-48.png"))); // NOI18N
        getContentPane().add(logoConsola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        netFramework452.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netFramework452.setForeground(new java.awt.Color(255, 255, 255));
        netFramework452.setText("NetFramework 4.5.2");
        netFramework452.setBorder(null);
        netFramework452.setFocusPainted(false);
        netFramework452.setOpaque(false);
        netFramework452.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netFramework452ActionPerformed(evt);
            }
        });
        getContentPane().add(netFramework452, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        netFramework4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netFramework4.setForeground(new java.awt.Color(255, 255, 255));
        netFramework4.setText("NetFramework 4.0");
        netFramework4.setBorder(null);
        netFramework4.setFocusPainted(false);
        netFramework4.setOpaque(false);
        netFramework4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netFramework4ActionPerformed(evt);
            }
        });
        getContentPane().add(netFramework4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        netFramework35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netFramework35.setForeground(new java.awt.Color(255, 255, 255));
        netFramework35.setText("NetFramework 3.5");
        netFramework35.setBorder(null);
        netFramework35.setFocusPainted(false);
        netFramework35.setOpaque(false);
        netFramework35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netFramework35ActionPerformed(evt);
            }
        });
        getContentPane().add(netFramework35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        imgAdorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PC5.png"))); // NOI18N
        getContentPane().add(imgAdorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crystalDiskInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crystalDiskInfoActionPerformed
        if (this.isSelected()) {
            herramientas.instalar("cmd /C start Extras/CrystalDiskInfo/DiskInfo32.exe");
        }
    }//GEN-LAST:event_crystalDiskInfoActionPerformed

    private void controlCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlCuentasActionPerformed
        if (this.isSelected()) {
            herramientas.instalar("cmd /C start UserAccountControlSettings.exe");
        }
    }//GEN-LAST:event_controlCuentasActionPerformed

    private void estadoBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoBateriaActionPerformed
        if (this.isSelected) {
            Procesos Buscador = new Procesos();
            String datoSistemaOperativo;
            try {
                datoSistemaOperativo = Buscador.consoleInfo("Nombre del sistema operativo:", "systeminfo");
                if (datoSistemaOperativo.contains("Microsoft Windows 1")) {
                    try {

                        Buscador.consoleInformation("Se ha guardado el informe", "powercfg /batteryreport");
                        JOptionPane.showMessageDialog(null, new JLabel("Se generó el reporte de la bateria", JLabel.CENTER), null, JOptionPane.PLAIN_MESSAGE);
                        herramientas.instalar("cmd /C start battery-report.html");

                    } catch (IOException ex) {
                        Logger.getLogger(herramientasPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, new JLabel("Esta característica no está disponible para su sistema operativo " + datoSistemaOperativo, JLabel.LEFT), null, JOptionPane.PLAIN_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(herramientasPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_estadoBateriaActionPerformed

    private void adminDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDispositivosActionPerformed
        if (this.isSelected()) {
            herramientas.instalar("cmd /C start devmgmt.msc");
        }
    }//GEN-LAST:event_adminDispositivosActionPerformed

    private void netFramework452ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netFramework452ActionPerformed
        if (this.isSelected()) {
            herramientas.instalar("cmd /C start /wait Extras/net4.5.2.exe");
        }
    }//GEN-LAST:event_netFramework452ActionPerformed

    private void netFramework4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netFramework4ActionPerformed
        if (this.isSelected()) {
            herramientas.instalar("cmd /C start /wait Extras/net4.0.exe");
        }
    }//GEN-LAST:event_netFramework4ActionPerformed

    private void netFramework35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netFramework35ActionPerformed
        if (this.isSelected()) {
            herramientas.instalar("cmd /C start /wait Extras/net3.5.exe");
        }
    }//GEN-LAST:event_netFramework35ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminDispositivos;
    private javax.swing.JRadioButton controlCuentas;
    private javax.swing.JRadioButton crystalDiskInfo;
    private javax.swing.JRadioButton estadoBateria;
    private javax.swing.JLabel imgAdorno;
    private javax.swing.JLabel logoConsola1;
    private javax.swing.JLabel logoNetFramework;
    private javax.swing.JLabel logoRayosX;
    private javax.swing.JRadioButton netFramework35;
    private javax.swing.JRadioButton netFramework4;
    private javax.swing.JRadioButton netFramework452;
    // End of variables declaration//GEN-END:variables
}
