/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instalador2021;

import java.awt.Menu;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Alejandro
 */
public class officePanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form officePanel
     */
    public officePanel() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        officeGroup = new javax.swing.ButtonGroup();
        InstalarOfficeBotton = new javax.swing.JButton();
        excelIcon = new javax.swing.JLabel();
        WordIcon = new javax.swing.JLabel();
        outlookIcon = new javax.swing.JLabel();
        powerPointIcon = new javax.swing.JLabel();
        office7x86 = new javax.swing.JRadioButton();
        office10x86 = new javax.swing.JRadioButton();
        office10x64 = new javax.swing.JRadioButton();
        office13x64 = new javax.swing.JRadioButton();
        office16x64 = new javax.swing.JRadioButton();
        office19x64 = new javax.swing.JRadioButton();
        imgAdorno = new javax.swing.JLabel();
        circulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(84, 115, 232));
        setBorder(null);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstalarOfficeBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        InstalarOfficeBotton.setText("Instalar");
        InstalarOfficeBotton.setBorder(null);
        InstalarOfficeBotton.setEnabled(false);
        InstalarOfficeBotton.setPreferredSize(new java.awt.Dimension(93, 29));
        InstalarOfficeBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstalarOfficeBottonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InstalarOfficeBottonMouseEntered(evt);
            }
        });
        InstalarOfficeBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstalarOfficeBottonActionPerformed(evt);
            }
        });
        getContentPane().add(InstalarOfficeBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 110, 30));

        excelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/microsoft-excel-2019-48.png"))); // NOI18N
        getContentPane().add(excelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        WordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/microsoft-word-2019-48.png"))); // NOI18N
        getContentPane().add(WordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        outlookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/microsoft-outlook-2019-48.png"))); // NOI18N
        getContentPane().add(outlookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        powerPointIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/microsoft-powerpoint-2019-48.png"))); // NOI18N
        getContentPane().add(powerPointIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        office7x86.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(office7x86);
        office7x86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        office7x86.setForeground(new java.awt.Color(255, 255, 255));
        office7x86.setText("Microsoft Office 2007 x86");
        office7x86.setBorder(null);
        office7x86.setContentAreaFilled(false);
        office7x86.setFocusPainted(false);
        office7x86.setFocusable(false);
        office7x86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                office7x86ActionPerformed(evt);
            }
        });
        getContentPane().add(office7x86, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, -1));

        office10x86.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(office10x86);
        office10x86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        office10x86.setForeground(new java.awt.Color(255, 255, 255));
        office10x86.setText("Microsoft Office 2010 x86");
        office10x86.setBorder(null);
        office10x86.setFocusPainted(false);
        office10x86.setOpaque(false);
        office10x86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                office10x86ActionPerformed(evt);
            }
        });
        getContentPane().add(office10x86, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 200, -1));

        office10x64.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(office10x64);
        office10x64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        office10x64.setForeground(new java.awt.Color(255, 255, 255));
        office10x64.setText("Microsoft Office 2010 x64");
        office10x64.setBorder(null);
        office10x64.setFocusPainted(false);
        office10x64.setOpaque(false);
        office10x64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                office10x64ActionPerformed(evt);
            }
        });
        getContentPane().add(office10x64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 200, -1));

        office13x64.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(office13x64);
        office13x64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        office13x64.setForeground(new java.awt.Color(255, 255, 255));
        office13x64.setText("Microsoft Office 2013 x64");
        office13x64.setBorder(null);
        office13x64.setFocusPainted(false);
        office13x64.setOpaque(false);
        office13x64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                office13x64ActionPerformed(evt);
            }
        });
        getContentPane().add(office13x64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        office16x64.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(office16x64);
        office16x64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        office16x64.setForeground(new java.awt.Color(255, 255, 255));
        office16x64.setText("Microsoft Office 2016 x64");
        office16x64.setBorder(null);
        office16x64.setFocusPainted(false);
        office16x64.setOpaque(false);
        office16x64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                office16x64ActionPerformed(evt);
            }
        });
        getContentPane().add(office16x64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, -1));

        office19x64.setBackground(new java.awt.Color(204, 204, 204));
        officeGroup.add(office19x64);
        office19x64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        office19x64.setForeground(new java.awt.Color(255, 255, 255));
        office19x64.setText("Microsoft Office 2019 x64");
        office19x64.setBorder(null);
        office19x64.setFocusPainted(false);
        office19x64.setOpaque(false);
        office19x64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                office19x64ActionPerformed(evt);
            }
        });
        getContentPane().add(office19x64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 200, -1));

        imgAdorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PC3.png"))); // NOI18N
        getContentPane().add(imgAdorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, 200));

        circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circulo.png"))); // NOI18N
        getContentPane().add(circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InstalarOfficeBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstalarOfficeBottonMouseClicked

    }//GEN-LAST:event_InstalarOfficeBottonMouseClicked

    private void InstalarOfficeBottonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstalarOfficeBottonMouseEntered

    }//GEN-LAST:event_InstalarOfficeBottonMouseEntered

    private void InstalarOfficeBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstalarOfficeBottonActionPerformed
        Instalador instalarOffice = new Instalador();
        if (office7x86.isSelected()) {
            instalarOffice.instalar("cmd /C start /wait Office/Office-2007/OFFICEENTERPRISE/SETUP.EXE");
        }

        if (office10x86.isSelected()) {
            instalarOffice.instalar("cmd /C start /wait Office/Office-2010/X86/setup.exe");
        }

        if (office10x64.isSelected()) {
            instalarOffice.instalar("cmd /C start /wait Office/Office-2010/X64/setup.exe");
        }

        if (office13x64.isSelected()) {
            instalarOffice.instalar("cmd /C start /wait Office/Office-2013/64/setup.exe");
        }

        if (office16x64.isSelected()) {
            instalarOffice.instalar("cmd /C start /wait Office/Office-2016/64/setup.exe");
        }

        if (office19x64.isSelected()) {

            DescomprimirZip Extractor = new DescomprimirZip();
            try {
                Extractor.DescomprimirCompleto("Office/Office-2019/OInstall.zip", "Office/Office-2019");
                instalarOffice.instalar("cmd /C start /wait Office/Office-2019/OInstall.exe");

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al descomprimir" + ex,"ERROR", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
                        
                    

    }//GEN-LAST:event_InstalarOfficeBottonActionPerformed

    private void office7x86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_office7x86ActionPerformed
       InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_office7x86ActionPerformed

    private void office10x86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_office10x86ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_office10x86ActionPerformed

    private void office10x64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_office10x64ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_office10x64ActionPerformed

    private void office13x64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_office13x64ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_office13x64ActionPerformed

    private void office16x64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_office16x64ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_office16x64ActionPerformed

    private void office19x64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_office19x64ActionPerformed
        InstalarOfficeBotton.setEnabled(true);
    }//GEN-LAST:event_office19x64ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InstalarOfficeBotton;
    private javax.swing.JLabel WordIcon;
    private javax.swing.JLabel circulo;
    private javax.swing.JLabel excelIcon;
    private javax.swing.JLabel imgAdorno;
    private javax.swing.JRadioButton office10x64;
    private javax.swing.JRadioButton office10x86;
    private javax.swing.JRadioButton office13x64;
    private javax.swing.JRadioButton office16x64;
    private javax.swing.JRadioButton office19x64;
    private javax.swing.JRadioButton office7x86;
    private javax.swing.ButtonGroup officeGroup;
    private javax.swing.JLabel outlookIcon;
    private javax.swing.JLabel powerPointIcon;
    // End of variables declaration//GEN-END:variables
}
