/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instalador2021;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Alejandro
 */
public class pantallaCarga extends javax.swing.JFrame {
    Timer t;
    ActionListener al;
    /**
     * Creates new form pantallaCarga
     */
    public pantallaCarga() {
                        
       
        al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jProgressBar1.setString("Cargando "+jProgressBar1.getValue()+"%");

                
                if (jProgressBar1.getValue()<=100){
                jProgressBar1.setValue(jProgressBar1.getValue()+10);
                jProgressBar1.setString("Cargando "+jProgressBar1.getValue()+"%");
                humanCharge.repaint();
                }
                else {
                t.stop(); 
                }
                if (jProgressBar1.getValue()>=100){
                aux();
                
                jProgressBar1.setValue(0);
                }
                
            }
        };
        t = new Timer(1000, al);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/iconoPC.png")).getImage());
        setBackground(new Color(0,0,0,0));
        jProgressBar1.setBackground(new Color(45,67,166));
        jProgressBar1.setForeground(new Color(24,42,126));
        UIManager.put("jProgressBar1.selectionForeground", Color.WHITE);
        jProgressBar1.setString("Cargando "+jProgressBar1.getValue()+"%");

        t.start();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        humanCharge = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barra.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instalador 2021");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        humanCharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barra.png"))); // NOI18N
        getContentPane().add(humanCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setToolTipText("");
        jProgressBar1.setPreferredSize(new java.awt.Dimension(148, 17));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 205, 23));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
  
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaCarga().setVisible(true);
            }
        });
    }
    
    public void aux(){
    this.dispose();
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel humanCharge;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
