/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instalador2021;

import java.awt.Menu;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Alejandro
 */
public class x32Panel extends javax.swing.JInternalFrame{
//principal aux = new principal();//objeto para pasar metodos
    cambioColor aux = new cambioColor();

    /**
     * Creates new form x64Panel
     */

    public x32Panel() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chromex32Ico = new javax.swing.JLabel();
        chromex32CheckBox = new javax.swing.JCheckBox();
        VLCx32Ico = new javax.swing.JLabel();
        VLCx32CheckBox = new javax.swing.JCheckBox();
        winrarx32Ico = new javax.swing.JLabel();
        winrarx32CheckBox = new javax.swing.JCheckBox();
        codecsIco = new javax.swing.JLabel();
        codecsCheckBox = new javax.swing.JCheckBox();
        adobeIco = new javax.swing.JLabel();
        adobeCheckBox = new javax.swing.JCheckBox();
        avastIco = new javax.swing.JLabel();
        avastCheckBox = new javax.swing.JCheckBox();
        visorFotosIco = new javax.swing.JLabel();
        visorFotosCheckBox = new javax.swing.JCheckBox();
        nitrox32Ico = new javax.swing.JLabel();
        nitrox32CheckBox = new javax.swing.JCheckBox();
        fireFoxx32Ico = new javax.swing.JLabel();
        fireFoxx32CheckBox = new javax.swing.JCheckBox();
        allChecksIco = new javax.swing.JLabel();
        allChecksCheckBox = new javax.swing.JCheckBox();
        Instalarx32Botton = new javax.swing.JButton();
        detenerInstalacionx64Botton = new javax.swing.JButton();
        imgAdorno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(84, 115, 232));
        setBorder(null);
        setForeground(new java.awt.Color(255, 255, 51));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chromex32Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chrome-48.png"))); // NOI18N
        getContentPane().add(chromex32Ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 23, -1, -1));

        chromex32CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        chromex32CheckBox.setSelected(true);
        chromex32CheckBox.setText("Chrome x32");
        chromex32CheckBox.setContentAreaFilled(false);
        chromex32CheckBox.setFocusPainted(false);
        chromex32CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chromex32CheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(chromex32CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 72, -1, -1));

        VLCx32Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vlc-48.png"))); // NOI18N
        getContentPane().add(VLCx32Ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 113, -1, -1));

        VLCx32CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        VLCx32CheckBox.setSelected(true);
        VLCx32CheckBox.setText("VLC Player x32");
        VLCx32CheckBox.setFocusPainted(false);
        VLCx32CheckBox.setOpaque(false);
        VLCx32CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLCx32CheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(VLCx32CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 162, -1, -1));

        winrarx32Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/winrar-48.png"))); // NOI18N
        getContentPane().add(winrarx32Ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 203, -1, -1));

        winrarx32CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        winrarx32CheckBox.setSelected(true);
        winrarx32CheckBox.setText("Winrar x32");
        winrarx32CheckBox.setFocusPainted(false);
        winrarx32CheckBox.setOpaque(false);
        winrarx32CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winrarx32CheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(winrarx32CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 252, -1, -1));

        codecsIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documentary-48B.png"))); // NOI18N
        getContentPane().add(codecsIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 293, -1, -1));

        codecsCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        codecsCheckBox.setText("Codecs A/V");
        codecsCheckBox.setFocusPainted(false);
        codecsCheckBox.setOpaque(false);
        codecsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codecsCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(codecsCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 342, -1, -1));

        adobeIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf-48.png"))); // NOI18N
        getContentPane().add(adobeIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 23, -1, -1));

        adobeCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        adobeCheckBox.setSelected(true);
        adobeCheckBox.setText("Adobe Reader");
        adobeCheckBox.setFocusPainted(false);
        adobeCheckBox.setOpaque(false);
        adobeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adobeCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(adobeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 72, -1, -1));

        avastIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avast-48.png"))); // NOI18N
        getContentPane().add(avastIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 113, -1, -1));

        avastCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        avastCheckBox.setSelected(true);
        avastCheckBox.setText("Avast Antivirus");
        avastCheckBox.setFocusPainted(false);
        avastCheckBox.setOpaque(false);
        avastCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avastCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(avastCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 162, -1, -1));

        visorFotosIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/photo-gallery-48B.png"))); // NOI18N
        getContentPane().add(visorFotosIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 203, -1, -1));

        visorFotosCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        visorFotosCheckBox.setText("Visor de Fotos");
        visorFotosCheckBox.setFocusPainted(false);
        visorFotosCheckBox.setOpaque(false);
        visorFotosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorFotosCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(visorFotosCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 252, -1, -1));

        nitrox32Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nitro-48B.png"))); // NOI18N
        getContentPane().add(nitrox32Ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 293, -1, -1));

        nitrox32CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        nitrox32CheckBox.setText("Nitro PDF x32");
        nitrox32CheckBox.setFocusPainted(false);
        nitrox32CheckBox.setOpaque(false);
        nitrox32CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitrox32CheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(nitrox32CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 342, -1, -1));

        fireFoxx32Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/firefox-48B.png"))); // NOI18N
        getContentPane().add(fireFoxx32Ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 23, -1, -1));

        fireFoxx32CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        fireFoxx32CheckBox.setText("FireFox x32");
        fireFoxx32CheckBox.setFocusPainted(false);
        fireFoxx32CheckBox.setOpaque(false);
        fireFoxx32CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireFoxx32CheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(fireFoxx32CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 72, -1, -1));

        allChecksIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index-48B.png"))); // NOI18N
        getContentPane().add(allChecksIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 113, -1, -1));

        allChecksCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        allChecksCheckBox.setText("Seleccionar todos");
        allChecksCheckBox.setFocusPainted(false);
        allChecksCheckBox.setOpaque(false);
        allChecksCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allChecksCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(allChecksCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 162, -1, -1));

        Instalarx32Botton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        Instalarx32Botton.setText("Instalar");
        Instalarx32Botton.setBorder(null);
        Instalarx32Botton.setPreferredSize(new java.awt.Dimension(93, 29));
        Instalarx32Botton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Instalarx32BottonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Instalarx32BottonMouseEntered(evt);
            }
        });
        Instalarx32Botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instalarx32BottonActionPerformed(evt);
            }
        });
        getContentPane().add(Instalarx32Botton, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 330, 110, 30));

        detenerInstalacionx64Botton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Stop.png"))); // NOI18N
        detenerInstalacionx64Botton.setText("Detener");
        detenerInstalacionx64Botton.setBorder(null);
        detenerInstalacionx64Botton.setPreferredSize(new java.awt.Dimension(93, 29));
        detenerInstalacionx64Botton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detenerInstalacionx64BottonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detenerInstalacionx64BottonMouseEntered(evt);
            }
        });
        detenerInstalacionx64Botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerInstalacionx64BottonActionPerformed(evt);
            }
        });
        getContentPane().add(detenerInstalacionx64Botton, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 330, 110, 30));

        imgAdorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PC2.png"))); // NOI18N
        getContentPane().add(imgAdorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 200, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chromex32CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chromex32CheckBoxActionPerformed
          if (chromex32CheckBox.isSelected()) {  
            aux.RegresarColorIcono(chromex32Ico);
        } else {
            aux.cambiarColorIcono(chromex32Ico);
        }
    }//GEN-LAST:event_chromex32CheckBoxActionPerformed

    private void VLCx32CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLCx32CheckBoxActionPerformed
          if (VLCx32CheckBox.isSelected()) {  
            aux.RegresarColorIcono(VLCx32Ico);
        } else {
            aux.cambiarColorIcono(VLCx32Ico);
        }
    }//GEN-LAST:event_VLCx32CheckBoxActionPerformed

    private void winrarx32CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winrarx32CheckBoxActionPerformed
          if (winrarx32CheckBox.isSelected()) {  
            aux.RegresarColorIcono(winrarx32Ico);
        } else {
            aux.cambiarColorIcono(winrarx32Ico);
        }
    }//GEN-LAST:event_winrarx32CheckBoxActionPerformed

    private void codecsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codecsCheckBoxActionPerformed
          if (codecsCheckBox.isSelected()) {  
            aux.RegresarColorIcono(codecsIco);
        } else {
            aux.cambiarColorIcono(codecsIco);
        }
    }//GEN-LAST:event_codecsCheckBoxActionPerformed

    private void adobeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adobeCheckBoxActionPerformed
          if (adobeCheckBox.isSelected()) {  
            aux.RegresarColorIcono(adobeIco);
        } else {
            aux.cambiarColorIcono(adobeIco);
        }
    }//GEN-LAST:event_adobeCheckBoxActionPerformed

    private void fireFoxx32CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireFoxx32CheckBoxActionPerformed
          if (fireFoxx32CheckBox.isSelected()) {  
            aux.RegresarColorIcono(fireFoxx32Ico);
        } else {
            aux.cambiarColorIcono(fireFoxx32Ico);
        }
    }//GEN-LAST:event_fireFoxx32CheckBoxActionPerformed

    private void avastCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avastCheckBoxActionPerformed
          if (avastCheckBox.isSelected()) {  
            aux.RegresarColorIcono(avastIco);
        } else {
            aux.cambiarColorIcono(avastIco);
        }
    }//GEN-LAST:event_avastCheckBoxActionPerformed

    private void visorFotosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorFotosCheckBoxActionPerformed
          if (visorFotosCheckBox.isSelected()) {  
            aux.RegresarColorIcono(visorFotosIco);
        } else {
            aux.cambiarColorIcono(visorFotosIco);
        }
    }//GEN-LAST:event_visorFotosCheckBoxActionPerformed

    private void nitrox32CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitrox32CheckBoxActionPerformed
          if (nitrox32CheckBox.isSelected()) {  
            aux.RegresarColorIcono(nitrox32Ico);
        } else {
            aux.cambiarColorIcono(nitrox32Ico);
        }
    }//GEN-LAST:event_nitrox32CheckBoxActionPerformed

    private void allChecksCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allChecksCheckBoxActionPerformed

        if (allChecksCheckBox.isSelected()) {
            allChecksCheckBox.setText("Deseleccionar todo");
            chromex32CheckBox.setSelected(true);
            VLCx32CheckBox.setSelected(true);
            winrarx32CheckBox.setSelected(true);
            codecsCheckBox.setSelected(true);
            adobeCheckBox.setSelected(true);
            avastCheckBox.setSelected(true);
            visorFotosCheckBox.setSelected(true);
            nitrox32CheckBox.setSelected(true);
            fireFoxx32CheckBox.setSelected(true);
            aux.RegresarColorIcono(allChecksIco);
            aux.RegresarColorIcono(chromex32Ico);
            aux.RegresarColorIcono(VLCx32Ico);
            aux.RegresarColorIcono(winrarx32Ico);
            aux.RegresarColorIcono(codecsIco);
            aux.RegresarColorIcono(adobeIco);
            aux.RegresarColorIcono(avastIco);
            aux.RegresarColorIcono(visorFotosIco);
            aux.RegresarColorIcono(nitrox32Ico);
            aux.RegresarColorIcono(fireFoxx32Ico);

            
            } 
        else {
            allChecksCheckBox.setText("Seleccionar todo");
            chromex32CheckBox.setSelected(false);
            VLCx32CheckBox.setSelected(false);
            winrarx32CheckBox.setSelected(false);
            codecsCheckBox.setSelected(false);
            adobeCheckBox.setSelected(false);
            avastCheckBox.setSelected(false);
            visorFotosCheckBox.setSelected(false);
            nitrox32CheckBox.setSelected(false);
            fireFoxx32CheckBox.setSelected(false);
            aux.cambiarColorIcono(allChecksIco);
            aux.cambiarColorIcono(chromex32Ico);
            aux.cambiarColorIcono(VLCx32Ico);
            aux.cambiarColorIcono(winrarx32Ico);
            aux.cambiarColorIcono(codecsIco);
            aux.cambiarColorIcono(adobeIco);
            aux.cambiarColorIcono(avastIco);
            aux.cambiarColorIcono(visorFotosIco);
            aux.cambiarColorIcono(nitrox32Ico);
            aux.cambiarColorIcono(fireFoxx32Ico);
    
        }
    
    

    }//GEN-LAST:event_allChecksCheckBoxActionPerformed

    private void Instalarx32BottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instalarx32BottonMouseClicked

    }//GEN-LAST:event_Instalarx32BottonMouseClicked

    private void Instalarx32BottonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instalarx32BottonMouseEntered

    }//GEN-LAST:event_Instalarx32BottonMouseEntered

    private void Instalarx32BottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instalarx32BottonActionPerformed
        activarDesactivarChecks(false);
        HiloX32 Instalacionx64 = new HiloX32(); 
        Instalacionx64.start();
        Instalarx32Botton.setVisible(false);
        detenerInstalacionx64Botton.setVisible(true);
        
        
       
    }//GEN-LAST:event_Instalarx32BottonActionPerformed

    private void detenerInstalacionx64BottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detenerInstalacionx64BottonMouseClicked

        
    }//GEN-LAST:event_detenerInstalacionx64BottonMouseClicked

    private void detenerInstalacionx64BottonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detenerInstalacionx64BottonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_detenerInstalacionx64BottonMouseEntered

    private void detenerInstalacionx64BottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerInstalacionx64BottonActionPerformed
        boolean confirmar=true;
                
        cerrarPrograma(confirmar);
        

        

    }//GEN-LAST:event_detenerInstalacionx64BottonActionPerformed
    
  
  class HiloX32 extends Thread {

        @Override
        public void run() {

            Instalador Software = new Instalador();

            int tiempo = 1000;
            boolean continuar = false;

            Procesos Buscador = new Procesos();

            if (chromex32CheckBox.isSelected()) {

                do {
                    try {
                        Thread.sleep(1 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("2.-Chrome32.exe")) {
                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/2.-Chrome32.exe", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
                            
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                        
                    }
                } while (continuar);

            }

            if (VLCx32CheckBox.isSelected()) {

                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome64.exe")) {

                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/3.-VLC32.exe /S", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
                             

                        }

                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);
            }
            if (winrarx32CheckBox.isSelected()) {
                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe")) {

                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/5.-WinrarX32.exe /S", 5);
                            Thread.sleep(3 * tiempo);
                            Software.instalarTiempo("cmd /C start /wait Activadores/WinrarCrackX32.exe /S", 3);
                            continuar = false;
                             
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);

            }
            if (codecsCheckBox.isSelected()) {
                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe") || Buscador.isProcessRunning("4.-Codec_Pack.exe")) {
                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/4.-Codec_Pack.exe /S", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
         
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);

            }
            if (adobeCheckBox.isSelected()) {
                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe") || Buscador.isProcessRunning("4.-Codec_Pack.exe") || Buscador.isProcessRunning("6.-Adobe.exe")) {
                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/6.-Adobe.exe", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);

            }

            if (avastCheckBox.isSelected()) {
                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe") || Buscador.isProcessRunning("4.-Codec_Pack.exe") || Buscador.isProcessRunning("6.-Adobe.exe") || Buscador.isProcessRunning("7.-Avast.exe")) {
                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/7.-Avast.exe", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);

            }

            if (visorFotosCheckBox.isSelected()) {
                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe") || Buscador.isProcessRunning("4.-Codec_Pack.exe") || Buscador.isProcessRunning("6.-Adobe.exe") || Buscador.isProcessRunning("7.-Avast.exe") || Buscador.isProcessRunning("Restore_Windows_Photo_Viewer.reg")) {
                        } else {
                            Software.instalarTiempo("cmd /C start /wait Extras/Restore_Windows_Photo_Viewer.reg", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);

            }

            if (nitrox32CheckBox.isSelected()) {
                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe") || Buscador.isProcessRunning("4.-Codec_Pack.exe") || Buscador.isProcessRunning("6.-Adobe.exe") || Buscador.isProcessRunning("7.-Avast.exe") || Buscador.isProcessRunning("Restore_Windows_Photo_Viewer.reg") || Buscador.isProcessRunning("9.-Nitrox32.exe")) {
                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/9.-Nitrox32.exe", 20);
                            Software.instalarTiempo("cmd /C start /wait Extras/Nitro.txt", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);

            }
            if (fireFoxx32CheckBox.isSelected()) {
                do {

                    try {
                        Thread.sleep(3 * tiempo);
                        continuar = true;
                        if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe") || Buscador.isProcessRunning("4.-Codec_Pack.exe") || Buscador.isProcessRunning("6.-Adobe.exe") || Buscador.isProcessRunning("7.-Avast.exe") || Buscador.isProcessRunning("Restore_Windows_Photo_Viewer.reg") || Buscador.isProcessRunning("9.-Nitrox32.exe") || Buscador.isProcessRunning("8.-FireFoxX32.exe")) {
                        } else {
                            Software.instalarTiempo("cmd /C start /wait 32/8.-FireFoxX32.exe", 1);
                            Thread.sleep(3 * tiempo);
                            continuar = false;
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } while (continuar);

            }

            

            do {

                try {
                    Thread.sleep(3 * tiempo);
                    continuar = true;
                    if (Buscador.isProcessRunning("5.-WinrarX32.exe") || Buscador.isProcessRunning("3.-VLC32.exe") || Buscador.isProcessRunning("2.-Chrome32.exe") || Buscador.isProcessRunning("4.-Codec_Pack.exe") || Buscador.isProcessRunning("6.-Adobe.exe") || Buscador.isProcessRunning("7.-Avast.exe") || Buscador.isProcessRunning("Restore_Windows_Photo_Viewer.reg") || Buscador.isProcessRunning("9.-Nitrox32.exe") || Buscador.isProcessRunning("8.-FireFoxX32.exe")) {
                    } else {
                        
                        JOptionPane.showMessageDialog(null,new JLabel("INSTALACIÓN TERMINADA", JLabel.CENTER), null, JOptionPane.PLAIN_MESSAGE);
                        activarDesactivarChecks(true);
                        continuar = false;
                        
                        
                        
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } while (continuar);
                        detenerInstalacionx64Botton.setVisible(false);
                        Instalarx32Botton.setVisible(true);
                       

            
        }

    }

    public void activarDesactivarChecks(boolean respuesta){
        chromex32CheckBox.setEnabled(respuesta);
        VLCx32CheckBox.setEnabled(respuesta);
        winrarx32CheckBox.setEnabled(respuesta);
        codecsCheckBox.setEnabled(respuesta);
        adobeCheckBox.setEnabled(respuesta);
        avastCheckBox.setEnabled(respuesta);
        visorFotosCheckBox.setEnabled(respuesta);
        nitrox32CheckBox.setEnabled(respuesta);
        fireFoxx32CheckBox.setEnabled(respuesta);
        allChecksCheckBox.setEnabled(respuesta);
        
  }   
  
  public boolean cerrarPrograma(boolean resultado){
int result = JOptionPane.showConfirmDialog(null,"Esta acción cerrara el programa ¿Desea continuar? ", "",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
            System.exit(0);
            resultado=true;
            }
            else resultado=false;
        return resultado;

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Instalarx32Botton;
    private javax.swing.JCheckBox VLCx32CheckBox;
    private javax.swing.JLabel VLCx32Ico;
    private javax.swing.JCheckBox adobeCheckBox;
    private javax.swing.JLabel adobeIco;
    private javax.swing.JCheckBox allChecksCheckBox;
    private javax.swing.JLabel allChecksIco;
    private javax.swing.JCheckBox avastCheckBox;
    private javax.swing.JLabel avastIco;
    private javax.swing.JCheckBox chromex32CheckBox;
    private javax.swing.JLabel chromex32Ico;
    private javax.swing.JCheckBox codecsCheckBox;
    private javax.swing.JLabel codecsIco;
    private javax.swing.JButton detenerInstalacionx64Botton;
    private javax.swing.JCheckBox fireFoxx32CheckBox;
    private javax.swing.JLabel fireFoxx32Ico;
    private javax.swing.JLabel imgAdorno;
    private javax.swing.JCheckBox nitrox32CheckBox;
    private javax.swing.JLabel nitrox32Ico;
    private javax.swing.JCheckBox visorFotosCheckBox;
    private javax.swing.JLabel visorFotosIco;
    private javax.swing.JCheckBox winrarx32CheckBox;
    private javax.swing.JLabel winrarx32Ico;
    // End of variables declaration//GEN-END:variables
}










